// <auto-generated />
using System;
using DailyDevotional.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DailyDevotional.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813174742_SeedDailyReadings")]
    partial class SeedDailyReadings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyDevotional.Api.Models.DailyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Passage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassageReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyReadings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Commentary = "God begins the story of creation by bringing order and light into darkness.",
                            Date = new DateOnly(2026, 8, 11),
                            Passage = "In the beginning God created the heavens and the earth...",
                            PassageReference = "Genesis 1:1-5"
                        },
                        new
                        {
                            Id = 2,
                            Commentary = "God continues bringing structure and distinction to creation.",
                            Date = new DateOnly(2026, 8, 12),
                            Passage = "And God said, Let there be a vault between the waters...",
                            PassageReference = "Genesis 1:6-10"
                        },
                        new
                        {
                            Id = 3,
                            Commentary = "Creation continues as God brings forth life and establishes the rhythms of the world.",
                            Date = new DateOnly(2026, 8, 13),
                            Passage = "Then God said, Let the land produce vegetation...",
                            PassageReference = "Genesis 1:11-15"
                        });
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FavoriteVerse")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassageReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Journals");
                });
#pragma warning restore 612, 618
        }
    }
}
