// <auto-generated />
using System;
using DailyDevotional.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DailyDevotional.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008042040_AddMultiTranslationSupport")]
    partial class AddMultiTranslationSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyDevotional.Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Testament")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GEN",
                            Name = "Genesis",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EXO",
                            Name = "Exodus",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 3,
                            Code = "LEV",
                            Name = "Leviticus",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 4,
                            Code = "NUM",
                            Name = "Numbers",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 5,
                            Code = "DEU",
                            Name = "Deuteronomy",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 6,
                            Code = "JOS",
                            Name = "Joshua",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 7,
                            Code = "JDG",
                            Name = "Judges",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 8,
                            Code = "RUT",
                            Name = "Ruth",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 9,
                            Code = "1SA",
                            Name = "1 Samuel",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 10,
                            Code = "2SA",
                            Name = "2 Samuel",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 11,
                            Code = "1KI",
                            Name = "1 Kings",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 12,
                            Code = "2KI",
                            Name = "2 Kings",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 13,
                            Code = "1CH",
                            Name = "1 Chronicles",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 14,
                            Code = "2CH",
                            Name = "2 Chronicles",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 15,
                            Code = "EZR",
                            Name = "Ezra",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 16,
                            Code = "NEH",
                            Name = "Nehemiah",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 17,
                            Code = "EST",
                            Name = "Esther",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 18,
                            Code = "JOB",
                            Name = "Job",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 19,
                            Code = "PSA",
                            Name = "Psalms",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 20,
                            Code = "PRO",
                            Name = "Proverbs",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 21,
                            Code = "ECC",
                            Name = "Ecclesiastes",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 22,
                            Code = "SNG",
                            Name = "Song of Songs",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 23,
                            Code = "ISA",
                            Name = "Isaiah",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 24,
                            Code = "JER",
                            Name = "Jeremiah",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 25,
                            Code = "LAM",
                            Name = "Lamentations",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 26,
                            Code = "EZK",
                            Name = "Ezekiel",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 27,
                            Code = "DAN",
                            Name = "Daniel",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 28,
                            Code = "HOS",
                            Name = "Hosea",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 29,
                            Code = "JOL",
                            Name = "Joel",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 30,
                            Code = "AMO",
                            Name = "Amos",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 31,
                            Code = "OBA",
                            Name = "Obadiah",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 32,
                            Code = "JON",
                            Name = "Jonah",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 33,
                            Code = "MIC",
                            Name = "Micah",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 34,
                            Code = "NAM",
                            Name = "Nahum",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 35,
                            Code = "HAB",
                            Name = "Habakkuk",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 36,
                            Code = "ZEP",
                            Name = "Zephaniah",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 37,
                            Code = "HAG",
                            Name = "Haggai",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 38,
                            Code = "ZEC",
                            Name = "Zechariah",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 39,
                            Code = "MAL",
                            Name = "Malachi",
                            Testament = "OT"
                        },
                        new
                        {
                            Id = 40,
                            Code = "MAT",
                            Name = "Matthew",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 41,
                            Code = "MRK",
                            Name = "Mark",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 42,
                            Code = "LUK",
                            Name = "Luke",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 43,
                            Code = "JHN",
                            Name = "John",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 44,
                            Code = "ACT",
                            Name = "Acts",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 45,
                            Code = "ROM",
                            Name = "Romans",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 46,
                            Code = "1CO",
                            Name = "1 Corinthians",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 47,
                            Code = "2CO",
                            Name = "2 Corinthians",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 48,
                            Code = "GAL",
                            Name = "Galatians",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 49,
                            Code = "EPH",
                            Name = "Ephesians",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 50,
                            Code = "PHP",
                            Name = "Philippians",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 51,
                            Code = "COL",
                            Name = "Colossians",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 52,
                            Code = "1TH",
                            Name = "1 Thessalonians",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 53,
                            Code = "2TH",
                            Name = "2 Thessalonians",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 54,
                            Code = "1TI",
                            Name = "1 Timothy",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 55,
                            Code = "2TI",
                            Name = "2 Timothy",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 56,
                            Code = "TIT",
                            Name = "Titus",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 57,
                            Code = "PHM",
                            Name = "Philemon",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 58,
                            Code = "HEB",
                            Name = "Hebrews",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 59,
                            Code = "JAS",
                            Name = "James",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 60,
                            Code = "1PE",
                            Name = "1 Peter",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 61,
                            Code = "2PE",
                            Name = "2 Peter",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 62,
                            Code = "1JN",
                            Name = "1 John",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 63,
                            Code = "2JN",
                            Name = "2 John",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 64,
                            Code = "3JN",
                            Name = "3 John",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 65,
                            Code = "JUD",
                            Name = "Jude",
                            Testament = "NT"
                        },
                        new
                        {
                            Id = 66,
                            Code = "REV",
                            Name = "Revelation",
                            Testament = "NT"
                        });
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.DailyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer");

                    b.Property<string>("Commentary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EndChapter")
                        .HasColumnType("integer");

                    b.Property<int>("EndVerse")
                        .HasColumnType("integer");

                    b.Property<int>("StartVerse")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyReadings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Chapter = 1,
                            Commentary = "God begins the creation story by bringing order and light into darkness.",
                            Date = new DateOnly(2026, 8, 11),
                            EndChapter = 0,
                            EndVerse = 5,
                            StartVerse = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Chapter = 1,
                            Commentary = "God continues bringing structure and distinction to creation.",
                            Date = new DateOnly(2026, 8, 12),
                            EndChapter = 0,
                            EndVerse = 10,
                            StartVerse = 6
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Chapter = 1,
                            Commentary = "Creation continues as God brings forth life and establishes the rhythms of the world.",
                            Date = new DateOnly(2026, 8, 13),
                            EndChapter = 0,
                            EndVerse = 15,
                            StartVerse = 11
                        });
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FavoriteVerse")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassageReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CopyrightNotice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaxCacheAgeDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxCachedVerses")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NonCommercialOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ESV",
                            CopyrightNotice = "Scripture quotations are from the ESV® Bible (The Holy Bible, English Standard Version®), © 2001 by Crossway, a publishing ministry of Good News Publishers. Used by permission. All rights reserved.",
                            IsEnabled = true,
                            Language = "en",
                            MaxCacheAgeDays = 14,
                            MaxCachedVerses = 500,
                            Name = "English Standard Version",
                            NonCommercialOnly = true,
                            ProviderKind = "EsvApi",
                            SortOrder = 1,
                            StorageMode = "Cache"
                        },
                        new
                        {
                            Id = 2,
                            Code = "KJV",
                            CopyrightNotice = "King James Version (public domain in the United States).",
                            IsEnabled = false,
                            Language = "en",
                            Name = "King James Version",
                            NonCommercialOnly = false,
                            ProviderKind = "Local",
                            SortOrder = 2,
                            StorageMode = "Full"
                        });
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.TranslationBook", b =>
                {
                    b.Property<int>("TranslationId")
                        .HasColumnType("integer");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("integer");

                    b.HasKey("TranslationId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("TranslationBooks");
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.TranslationChapter", b =>
                {
                    b.Property<int>("TranslationId")
                        .HasColumnType("integer");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer");

                    b.Property<int>("VerseCount")
                        .HasColumnType("integer");

                    b.HasKey("TranslationId", "BookId", "Chapter");

                    b.HasIndex("BookId");

                    b.ToTable("TranslationChapters");
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnableAiCommentary")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableSearchInHistory")
                        .HasColumnType("boolean");

                    b.Property<int>("PreferredTranslationId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShareFavoriteVerseInHistory")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShareHistory")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFavoriteVerseInNotes")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PreferredTranslationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.Verse", b =>
                {
                    b.Property<int>("TranslationId")
                        .HasColumnType("integer");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TranslationId", "BookId", "Chapter", "VerseNumber");

                    b.HasIndex("BookId");

                    b.HasIndex("TranslationId", "FetchedAt");

                    b.ToTable("Verses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.DailyReading", b =>
                {
                    b.HasOne("DailyDevotional.Api.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.TranslationBook", b =>
                {
                    b.HasOne("DailyDevotional.Api.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyDevotional.Api.Models.Translation", "Translation")
                        .WithMany()
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.TranslationChapter", b =>
                {
                    b.HasOne("DailyDevotional.Api.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyDevotional.Api.Models.Translation", "Translation")
                        .WithMany()
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.UserSettings", b =>
                {
                    b.HasOne("DailyDevotional.Api.Models.Translation", null)
                        .WithMany()
                        .HasForeignKey("PreferredTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyDevotional.Api.Models.Verse", b =>
                {
                    b.HasOne("DailyDevotional.Api.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyDevotional.Api.Models.Translation", "Translation")
                        .WithMany()
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DailyDevotional.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DailyDevotional.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyDevotional.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DailyDevotional.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
